### ISSUE TITLE
Timeline, Comments, and Like button back-end and front-end Implementation in Index Page

### ISSUE THREAD

**Issue by MrLucky44** [g3yk/Lockify#6]
These sections has to be in **index.html.erb**

**Comment by g3yk** [comment]
We are waiting @berkayacar to accept our invitation and then he will handle this issue

**Comment by MrLucky44** [comment]
We are waiting @berkayacar to accept our invitation and then he will handle this enhancement!

**Comment by MrLucky44** [comment]
@g3yk Okay, then we will wait him.

**Comment by berkayacar** [comment]
ne oldu la
________________________________
Gönderen: Ali Kerem Erhan ***@***.***>
Gönderildi: 26 Aralık 2024 Perşembe 14:48
Kime: g3yk/Lockify ***@***.***>
Bilgi: berkayacar ***@***.***>; Mention ***@***.***>
Konu: Re: [g3yk/Lockify] Timeline, Comments, and Like button back-end and front-end Implementation in Index Page (Issue #6)


@g3yk<https://github.com/g3yk> Okay, then we will wait him.

**Comment by berkayacar** [comment]
olm bunu sen yapmayacak mıydın?
________________________________
Gönderen: emre ***@***.***>
Gönderildi: 26 Aralık 2024 Perşembe 21:54
Kime: g3yk/Lockify ***@***.***>
Bilgi: berkayacar ***@***.***>; Assign ***@***.***>
Konu: Re: [g3yk/Lockify] Timeline, Comments, and Like button back-end and front-end Implementation in Index Page (Issue #6)


Assigned #6<https://github.com/g3yk/Lockify/issues/6> to @berkayacar<https://github.com/berkayacar>.

**Comment by g3yk** [comment]
Timeline'ı yaparım dahasına karışmam ben.

**Comment by MrLucky44** [comment]
Top bana gelecek gibi gelmesin arkadaşlar mümkünse

**Comment by berkayacar** [comment]
ben kalanı yaparım ama patlayabilir proje haberiniz olsun
________________________________
Gönderen: Ali Kerem Erhan ***@***.***>
Gönderildi: 26 Aralık 2024 Perşembe 22:25
Kime: g3yk/Lockify ***@***.***>
Bilgi: berkayacar ***@***.***>; Mention ***@***.***>
Konu: Re: [g3yk/Lockify] Timeline, Comments, and Like button back-end and front-end Implementation in Index Page (Issue #6)


Top bana gelecek gibi gelmesin arkadaşlar mümkünse

**Comment by g3yk** [comment]
I have successfully implemented the timeline and like button on the index page, including both UI and back-end components. Everything is functioning as expected.

I will now proceed to close this issue. Thank you! Feel free to modify it if you need to add any additional details!

**Comment by g3yk** [comment]
I have successfully implemented the timeline and like button on the index page, including both UI and back-end components. Everything is functioning as expected.

I will now proceed to close this issue. Thank you! Feel free to modify it if you need to add any additional details!

**Comment by berkayacar** [comment]
Hi Emre,

Thank you for your effort, project will be working successfully in the presentation.


King Regards,

Berkay Acar
________________________________
Gönderen: emre ***@***.***>
Gönderildi: 27 Aralık 2024 Cuma 14:55
Kime: g3yk/Lockify ***@***.***>
Bilgi: berkayacar ***@***.***>; Mention ***@***.***>
Konu: Re: [g3yk/Lockify] Timeline, Comments, and Like button back-end and front-end Implementation in Index Page (Issue #6)


I have successfully implemented the timeline and like button on the index page, including both UI and back-end components. Everything is functioning as expected.

I will now proceed to close this issue. Thank you! Feel free to modify it if you need to add any additional details!
